language: c++

dist: bionic

cache:
  directories:
    - /home/travis/creativexx/vendor

matrix:
  include:
    - os: linux
      compiler:
        - gcc
        - clang
      addons:
        apt:
          packages:
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - freeglut3-dev
            - mesa-common-dev
            - clang-format
            - python3
            - pip3

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - alias python3 python
  - alias pip3 pip
  - python --version
  - pip --version
  - cd vendor/pytorch
  - pip install -r requirements.txt
  - python setup.py develop
  - cd ../..
  - pip install -r requirements.txt

script:
  - python cli/cli.py --verbose build && python cli/cli.py --verbose format && python cli/cli.py --verbose all_tests --ci