name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: ubuntu_requirements
      run: ./scripts/linux/ubuntu.sh

    - name: python_requirements
      run: pip3 install -r requirements.txt

    - name: build_pytorch
      run: cd ${{github.workspace}}/vendor/pytorch && pip3 install requirements.txt && python setup.py develop && cd ${{github.workspace}}

  format:
    needs: [setup]
    steps:
    - name: format
      run: cd ${{github.workspace}} && python cli/cli.py --verbose --ci format

  build:
    needs: [setup]
    steps:
    - name: build
      run: cd ${{github.workspace}} && python cli/cli.py --verbose --ci build

  test:
    needs: [setup, build]
    steps:
    - name: test
      run: cd ${{github.workspace}} && python cli/cli.py --verbose --ci all_tests
      