name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

    - name: ubuntu_requirements
      run: sh ${{github.workspace}}/scripts/linux/ubuntu-install.sh

    - name: python_requirements
      run: pip3 install -r requirements.txt

    - name: format
      run: python3 ${{github.workspace}}/cli/cli.py --verbose --ci format

    - name: submodule_info
      run: git submodule status > ${{github.workspace}}/submodule_info.txt

    - name: cache_pytorch
      id: cache-pytorch
      uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/vendor/pytorch
        key: ${{ runner.os }}-${{ hashFiles(git submodule status) }}
        restore-keys: |
          ${{ runner.os }}-${{ hashFiles(git submodule status) }}

    - name: change_permissions
      run: sudo chmod a+w /usr/local/lib/python3.8/dist-packages/

    - name: pytorch_requirements
      working-directory: ${{github.workspace}}/vendor/pytorch
      run: pip3 install -r requirements.txt

    - name: pytorch_build
      working-directory: ${{github.workspace}}/vendor/pytorch
      run: USE_CUDA=0 python3 setup.py develop
  
    - name: build
      run: python3 ${{github.workspace}}/cli/cli.py --verbose --ci build

    - name: test
      run: python3 ${{github.workspace}}/cli/cli.py --verbose --ci all_tests
      