name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: ubuntu_requirements
      run: sh ${{github.workspace}}/scripts/linux/ubuntu-install.sh

    - name: python_requirements
      run: pip3 install -r requirements.txt

  pytorch:
    runs-on: ubuntu-latest
    needs: [setup]
    defaults:
      run:
        working-directory: ${{github.workspace}}/vendor/pytorch
    steps:
    - name: python_requirements
      run: which bash && python3 --version && pip3 install -r requirements.txt
    - name: build
      run: python3 setup.py develop
  
  format:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
    - name: format
      run: python3 ${{github.workspace}}/cli/cli.py --verbose --ci format

  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{github.workspace}}

    needs: [setup, pytorch]
    steps:
    - name: build
      run: python3 ${{github.workspace}}/cli/cli.py --verbose --ci build

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: test
      run: python3 ${{github.workspace}}/cli/cli.py --verbose --ci all_tests
      