name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: ubuntu_requirements
      run: sh ${{github.workspace}}/scripts/linux/ubuntu-install.sh

    - name: python_requirements
      run: pip3 install -r requirements.txt

    - name: format
      run: python3 ${{github.workspace}}/cli/cli.py --verbose --ci format

    - name: pytorch_requirements
      working-directory: ${{github.workspace}}/vendor/pytorch
      run: which bash && python3 --version && pip3 install -r requirements.txt

    - name: pytorch_build
      working-directory: ${{github.workspace}}/vendor/pytorch
      run: python3 setup.py develop
  
    - name: build
      run: python3 ${{github.workspace}}/cli/cli.py --verbose --ci build

    - name: test
      run: python3 ${{github.workspace}}/cli/cli.py --verbose --ci all_tests
      