name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: ubuntu_requirements
      run: sh ${{github.workspace}}/scripts/linux/ubuntu-install.sh

    - name: python_requirements
      run: pip3 install -r requirements.txt

    - name: build_pytorch
      working-directory: ${{github.workspace}}/vendor/pytorch
      run: pip3 install requirements.txt && python setup.py develop

  format:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
    - name: format
      run: python ${{github.workspace}}/cli/cli.py --verbose --ci format

  build:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
    - name: build
      run: python ${{github.workspace}}/cli/cli.py --verbose --ci build

  test:
    runs-on: ubuntu-latest
    needs: [setup, build]
    steps:
    - name: test
      run: python ${{github.workspace}}/cli/cli.py --verbose --ci all_tests
      